# Generated by Django 3.2.4 on 2021-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCpuPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('user_percent', models.FloatField(verbose_name='用户CPU占用百分比')),
            ],
        ),
    ]
